
export const potentialGame = {
  'a1': 'white_rook',
  'b1': 'white_knight',
  'c1': 'white_bishop',
  'd1': 'white_fool',
  'e1': 'white_king',
  'f1': 'white_queen',
  'g1': 'white_toad',
  'h1': 'white_bishop',
  'i1': 'white_knight',
  'j1': 'white_rook',
  'a2': 'white_pawn',
  'b2': 'white_pawn',
  'c2': 'white_pawn',
  'd2': 'white_pawn',
  'e2': 'white_pawn',
  'f2': 'white_pawn',
  'g2': 'white_pawn',
  'h2': 'white_pawn',
  'i2': 'white_pawn',
  'j2': 'white_pawn',

  'a10': 'black_rook',
  'b10': 'black_knight',
  'c10': 'black_bishop',
  'd10': 'black_fool',
  'e10': 'black_king',
  'f10': 'black_queen',
  'g10': 'black_toad',
  'h10': 'black_bishop',
  'i10': 'black_knight',
  'j10': 'black_rook',
  'a9': 'black_pawn',
  'b9': 'black_pawn',
  'c9': 'black_pawn',
  'd9': 'black_pawn',
  'e9': 'black_pawn',
  'f9': 'black_pawn',
  'g9': 'black_pawn',
  'h9': 'black_pawn',
  'i9': 'black_pawn',
  'j9': 'black_pawn',
}
